#!/usr/bin/env python3
"""Refresh data/scholar.yaml from the Google Scholar profile.

Scholar has no API, so this parses the public profile page. It is best-effort
by design: Google rate-limits and CAPTCHAs datacenter IPs, so any failure
leaves the committed data/scholar.yaml untouched and exits 0. The site then
keeps rendering the last numbers that were successfully fetched rather than
losing them on a bad day.

Per-paper counts are matched back to data/research.yaml here, in Python,
rather than in a Hugo template — Scholar lowercases titles and drops some
punctuation, which is awkward to reconcile in template logic.
"""

import datetime
import html
import pathlib
import re
import sys
import urllib.error
import urllib.request

import yaml

PROFILE_ID = "hN5V_WUAAAAJ"
PROFILE_URL = f"https://scholar.google.com/citations?user={PROFILE_ID}&hl=en"
FETCH_URL = f"{PROFILE_URL}&cstart=0&pagesize=100"
UA = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0 Safari/537.36"
)

ROOT = pathlib.Path(__file__).resolve().parent.parent
RESEARCH = ROOT / "data" / "research.yaml"
OUTPUT = ROOT / "data" / "scholar.yaml"


def give_up(reason):
    print(f"scholar: {reason} — keeping the existing {OUTPUT.name}")
    sys.exit(0)


def text_of(fragment):
    return html.unescape(re.sub(r"<[^>]+>", "", fragment)).strip()


def key_of(title):
    return re.sub(r"[^a-z0-9]+", "", title.lower())


def fetch(url):
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request, timeout=45) as response:
        return response.read().decode("utf-8", "replace")


def parse_papers(page):
    papers = []
    for row in re.findall(r'<tr class="gsc_a_tr">(.*?)</tr>', page, re.S):
        title = re.search(r'class="gsc_a_at"[^>]*>(.*?)</a>', row, re.S)
        cites = re.search(r'class="gsc_a_ac[^"]*"[^>]*>(.*?)</a>', row, re.S)
        if not title:
            continue
        count = text_of(cites.group(1)) if cites else ""
        papers.append((text_of(title.group(1)), int(count) if count.isdigit() else 0))
    return papers


def match_to_research(papers):
    """Map each data/research.yaml title to its Scholar citation count."""
    research = yaml.safe_load(RESEARCH.read_text(encoding="utf-8")) or {}
    by_key = {key_of(t): c for t, c in papers}

    matched, missing = {}, []
    for item in research.get("items", []):
        title = item.get("title", "")
        key = key_of(title)
        if key in by_key:
            matched[title] = by_key[key]
            continue
        # Scholar occasionally clips a long title; fall back to prefix overlap.
        hit = next(
            (c for k, c in by_key.items() if k.startswith(key[:40]) or key.startswith(k[:40])),
            None,
        )
        if hit is None:
            missing.append(title)
        else:
            matched[title] = hit
    return matched, missing


def main():
    try:
        page = fetch(FETCH_URL)
    except (urllib.error.URLError, TimeoutError, OSError) as error:
        give_up(f"could not reach Scholar ({error})")

    if re.search(r"not a robot|unusual traffic", page, re.I):
        give_up("Scholar served a CAPTCHA")

    totals = re.findall(r'<td class="gsc_rsb_std">(\d+)</td>', page)
    if len(totals) < 6:
        give_up("profile page had no citation table")

    papers = parse_papers(page)
    if not papers:
        give_up("profile page listed no papers")

    matched, missing = match_to_research(papers)
    for title in missing:
        print(f"scholar: no Scholar entry matched {title!r}")

    document = {
        "updated": datetime.date.today().isoformat(),
        "profile": PROFILE_URL,
        "citations": int(totals[0]),
        "h_index": int(totals[2]),
        "i10_index": int(totals[4]),
        "papers": matched,
    }

    OUTPUT.write_text(
        "# Generated by scripts/fetch_scholar.py — do not edit by hand.\n"
        + yaml.safe_dump(document, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    print(
        f"scholar: {document['citations']} citations, h-index {document['h_index']}, "
        f"{len(matched)}/{len(papers)} papers matched"
    )


if __name__ == "__main__":
    main()
